### ISSUE TITLE
danet new throw errors

### ISSUE THREAD

**Issue by elycheikhsmail** [Savory/Danet-CLI#2]
context:
OS: Windows 11
deno version:
   deno 1.32.3 (release, x86_64-pc-windows-msvc)
    v8 11.2.214.9
   typescript 5.0.3
danet cli version: ?
command: danet new  --in-memory danetapp
---
Error:
`
 danet new  --in-memory danetapp
Sun, 02 Apr 2023 21:55:20 GMT [Danet-CLI]  Cloning starter project from https://github.com/Savory/Danet-Starter.git into danetapp
Sun, 02 Apr 2023 21:55:22 GMT [Danet-CLI]  Keeping code as is due to in-memory being selected
Sun, 02 Apr 2023 21:55:22 GMT [Danet-CLI]  Deleting database folder
Sun, 02 Apr 2023 21:55:22 GMT [Danet-CLI]  Danet's project creation done !
  You can run it with the following commands: cd danetapp && deno task launch-server
  Tests can be run with: deno task test
error: Uncaught Error: Deno.core.runMicrotasks() is not supported in this environment
      throw new Error(
            ^
    at Object.runMicrotasks (https://deno.land/std@0.170.0/node/_core.ts:22:13)
    at processTicksAndRejections (https://deno.land/std@0.170.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.170.0/node/process.ts:375:7
    at innerInvokeEventListeners (ext:deno_web/02_event.js:783:7)
    at invokeEventListeners (ext:deno_web/02_event.js:823:5)
    at dispatch (ext:deno_web/02_event.js:692:9)
    at dispatchEvent (ext:deno_web/02_event.js:1082:12)
    at [ext:cli\worker.rs:90:38]:1:1
`

**Comment by elycheikhsmail** [comment]
I work now
